### ISSUE TITLE
Assembly step

### ISSUE THREAD

**Issue by CaroleBelliardo** [PacificBiosciences/pb-metagenomics-tools#11]
Hello,

I would like to know if you could advise me on options to use for metagenomic assembly with the assembler tool hifiasm?
Thanks a lot, 
Best regards

**Comment by dportik** [comment]
Hello,
You can obtain the metagenomic version of hifiasm from:
https://github.com/lh3/hifiasm-meta

The default parameters work well for most samples:
```
hifiasm_meta -t [threads] -o [output prefix] [HiFi Reads].fq.gz 2> [name].log
```
Here you would supply values to the brackets for your own dataset.

**Comment by CaroleBelliardo** [comment]
Thank you for your answer.
