### ISSUE TITLE
Checkm completeness and contaminantion??

### ISSUE THREAD

**Issue by rjsorr** [PacificBiosciences/pb-metagenomics-tools#18]
Interesting pipeline. Just wondering if you looked at other tools for evaluating MAG contaminant and completeness other than checkm? Checkm is a nice tool but it's results are based on a database comparison, and the database is out dated. And is this tool need when using long read data with low assembly error? Good to basemark it using this data though

**Comment by dportik** [comment]
Thank you for your comments. Do you have a recommendation for an alternative tool besides CheckM? 

I am not sure I understand your question. CheckM is used to assess completeness based on single copy orthologous markers. This is required to check any bacterial contig, regardless of sequencing technology, as we are after highly complete bacterial genomes from a given assembly.
