### ISSUE TITLE
java.lang.NullPointerException. jloda.graph.Node.getInfo()" because "v" is null

### ISSUE THREAD

**Issue by mianlee** [PacificBiosciences/pb-metagenomics-tools#21]
Dear author:

I was running MEGAN-RMA-summary, and then encountered the following errors. My system is CentOS7.

Do you have any idea why this is happening?
<img width="1634" alt="Screen Shot 2022-07-30 at 23 53 07" src="https://user-images.githubusercontent.com/32915883/181925013-4ff482e2-163a-4ee0-824a-4df32beab648.png">

Thank you so much!!!!

Best
Mian

**Comment by dportik** [comment]
@mianlee it looks like you've closed this issue - were you able to identify the problem?

**Comment by mianlee** [comment]
Hello :

Yes, it was just using different version of MEGAN database. I had some samples runing using old database with new version of MEGAN.  After I rerun all samples with the lastest database, it worked out.

Best
Mian
