### ISSUE TITLE
Error in rule RunGTDBTkIndividual

### ISSUE THREAD

**Issue by Metag3nOmics** [PacificBiosciences/pb-metagenomics-tools#23]
Hi,

I'm running into the following issue with the HiFi-MAG-Pipeline (see log file attached)

Already tried to find the problem but it still persists.

Kind regards.

[htu.RunGTDBTkIndividual.log](https://github.com/PacificBiosciences/pb-metagenomics-tools/files/9953213/htu.RunGTDBTkIndividual.log)

**Comment by dportik** [comment]
Hell @Metag3nOmics ,
It looks like pplacer is failing because the temporary directory you've specified does not exist. In the `config.yaml`, you'll want to change the following section:

```
# The path to use as the temporary directory to write large files to, which is used with the
# --tmpdir flag in checkm, and the --scratch_dir flag in gtdb. If using HPC, use "/scratch" 
# if you have access. If you do not have access to "/scratch" on HPC or are running 
# snakemake locally, change to a valid directory.
tmpdir: "/scratch"
```

Instead of `/scratch`, use a different directory. Let me know if that solves the issue.

**Comment by Metag3nOmics** [comment]
Hey dportik,

even after giving a different path to a valid directory it shows the same error (see logfile attached). I also checked if enough memory was available frp pplacer (was more than enough). 
[n9.RunGTDBTkIndividual.log](https://github.com/PacificBiosciences/pb-metagenomics-tools/files/9991023/n9.RunGTDBTkIndividual.log)

**Comment by dportik** [comment]
Hello @Metag3nOmics,
Thanks for double-checking this. Based on the log file you've sent, there might be additional error reporting available in `7-gtdb-individual/n9/classify/intermediate_results/pplacer/pplacer.high.bac120.out`. Would you be able to track this down and send it too? That will help narrow things down more.

**Comment by Metag3nOmics** [comment]
Hello dportik,

There is no such directory or file. I think all the files are cleared once the run was aborted. See below all the files i found in the n9 folder.
[gtdbtk.log](https://github.com/PacificBiosciences/pb-metagenomics-tools/files/10010697/gtdbtk.log)
[gtdbtk.warnings.log](https://github.com/PacificBiosciences/pb-metagenomics-tools/files/10010698/gtdbtk.warnings.log)

**Comment by dportik** [comment]
Hi @Metag3nOmics ,
According to the `gtdbtk.log`, there was an issue with `pplacer` again. We will need to see the logs from pplacer, otherwise this will be difficult to diagnose. You can try running again with the `--ignore-incomplete` command to see if it retains the outputs for the failed rule, or monitor the outputs and grab the log before it is deleted.
