### ISSUE TITLE
Re-running pipeline with adjusted completeness/contamination thresholds?

### ISSUE THREAD

**Issue by kkowalden** [PacificBiosciences/pb-metagenomics-tools#24]
Hello,

Is there an easy way to re-run the pipeline with adjusted completeness, contamination, and max contigs/bin cut-offs without completely starting over at the first steps?  
For example, after running the pipeline with default parameters, I'd like to evaluate bins with relaxed completeness/contamination thresholds.  
Does that require an entirely new run? Or can I adjust parameters in the config.yaml and have the pipeline re-run only the downstream steps that would be affected by the adjustments?

Thanks,
Kim

**Comment by dportik** [comment]
Hi @kkowalden ,
Currently the easiest way to complete this task is to move all folders starting with `6-checkm-summary` out of the snakemake directory to trigger a re-run of those steps. If you update the config file with different settings, those will be used to run the CheckM summary step, GTDB-Tk, and summary steps with the updated settings.

I can work on amending the names of those directories to include the completeness/contamination/contig values. This would allow the user to update these settings and re-run to produce the outputs in the same directory as a previously completed run.

**Comment by kkowalden** [comment]
Hi @dportik ,

I'm testing the pipeline now with the updated config file settings.

One observation thus far: it doesn't appear that the final plots generated are using the modified parameters for the XY axes.
For example, if I adjust the config file to: "min_completeness: 50", the final plots describing completeness retain "70" as the left-most tick mark on the X axis.

Kim

**Comment by dportik** [comment]
Hi @kkowalden,
It looks like those axes were accidentally fixed to the default values. I went ahead and updated the snakefile and plotting script so it should work now.

Please let me know if this fixes your issue. I am planning on working on the directory naming next.

**Comment by kkowalden** [comment]
Hi @dportik,

I updated the snakefile and plotting script (and my config.yaml file) in the pipeline directory and started the run from the very beginning.
Unfortunately, the final plots still retain the default "min_completeness: 70" for the X axis left-most tick mark.
Is there another script or file that needs to be updated to over-ride the final summary plot values?
Kim

**Comment by kkowalden** [comment]
I'm also now observing fatal errors in pplacer/gtdbtk after modifying the "min_completeness" parameter to 50.
I don't think it is a memory issue, but let me know if you have seen this before.

==> Step 1 of 9: Starting pplacer.Uncaught exception: Sys_error("/home/groups/hpcbio/data/GTDB/R207_v2/release207_v2/split/high/pplacer/gtdbtk_package_backbone.refpkg: No such file or directory")

**Comment by dportik** [comment]
Hi @kkowalden,
I would download all of the files in the `scripts/` directory - there are two plotting scripts that are used along the way. It's possible you only grabbed one of them?

I'm not sure what that error is related to - I haven't seen it yet. Let me know if it persists.

**Comment by kkowalden** [comment]
Hi @dportik ,

The most recent run with the updated files finished completely and correctly.
Thanks for your help!

Kim

**Comment by dportik** [comment]
Hi @kkowalden,
Great! Thanks for letting me know - I'll go ahead and close this issue.
