### ISSUE TITLE
HiFi-MAG-Pipeline: KeyError: 'min_contig_size'

### ISSUE THREAD

**Issue by YenlingPeng** [PacificBiosciences/pb-metagenomics-tools#36]
Hi,

I'm running into the following issue with the HiFi-MAG-Pipeline v1.6.0.

I just test workflow with the following command:
snakemake -np --snakefile Snakefile-hifimags --configfile configs/Sample-Config.yaml

and got the KeyError message.
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/63987863/213126959-e2e6334e-de4b-4821-a336-94c983f7d9ac.png">

I use [ATCC MSA-1003](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA546278/) as input data.

Thank you.

**Comment by dportik** [comment]
Hi @YenlingPeng ,
I'm not able to reproduce this error on my side. Can you please attach or copy/paste the contents of `config.yaml` here?

**Comment by dportik** [comment]
Hi @YenlingPeng ,
The `config.yaml` you are using appears to be outdated (v1.5). 

You will need to use the new version of this config file (https://github.com/PacificBiosciences/pb-metagenomics-tools/blob/master/HiFi-MAG-Pipeline/config.yaml), which is included in the HiFi-MAG-Pipeline directory. 

The same will be true for all the files - there were changes to items in the `scripts/` folder as well.

When using the newest version of the pipelines, please make sure to download all the associated files, and not just the snakemake file.

Please update all files and let me know if any errors persist.

**Comment by YenlingPeng** [comment]
Hi @dportik,

I upgraded to the latest version (v1.6) and re-running pipeline.

But, I get new error message.

`Error in rule ConcoctAnalysis:
    jobid: 20
    output: /data2/PB/Metagenomics/pb-metagenomics-tools-1.6.0/HiFi-MAG-Pipeline/3-concoct/atcc-msa-1003, /data2/PB/Metagenomics/pb-metagenomics-tools-1.6.0/HiFi-MAG-Pipeline/3-concoct/atcc-msa-1003/clustering_gt50000.csv
    log: /data2/PB/Metagenomics/pb-metagenomics-tools-1.6.0/HiFi-MAG-Pipeline/logs/atcc-msa-1003.ConcoctAnalysis.log (check log file(s) for error message)
    conda-env: /data2/PB/Metagenomics/pb-metagenomics-tools-1.6.0/HiFi-MAG-Pipeline/.snakemake/conda/d8dcd29ee246a470a1610d178025c180
    shell:
        concoct --composition_file /data2/PB/Metagenomics/pb-metagenomics-tools-1.6.0/HiFi-MAG-Pipeline/3-concoct/atcc-msa-1003.contigs_cut.fasta --coverage_file /data2/PB/Metagenomics/pb-metagenomics-tools-1.6.0/HiFi-MAG-Pipeline/3-concoct/atcc-msa-1003.coverage_table.tsv -l 50000 -b /data2/PB/Metagenomics/pb-metagenomics-tools-1.6.0/HiFi-MAG-Pipeline/3-concoct/atcc-msa-1003 -t 24 2> /data2/PB/Metagenomics/pb-metagenomics-tools-1.6.0/HiFi-MAG-Pipeline/logs/atcc-msa-1003.ConcoctAnalysis.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job ConcoctAnalysis since they might be corrupted:
/data2/PB/Metagenomics/pb-metagenomics-tools-1.6.0/HiFi-MAG-Pipeline/3-concoct/atcc-msa-1003
[Mon Jan 30 14:40:34 2023]
Error in rule MaxbinDepths:
    jobid: 18
    output: /data2/PB/Metagenomics/pb-metagenomics-tools-1.6.0/HiFi-MAG-Pipeline/2-bam/atcc-msa-1003.maxbin.depth.txt
    log: /data2/PB/Metagenomics/pb-metagenomics-tools-1.6.0/HiFi-MAG-Pipeline/logs/atcc-msa-1003.MaxbinDepths.log (check log file(s) for error message)
    conda-env: /data2/PB/Metagenomics/pb-metagenomics-tools-1.6.0/HiFi-MAG-Pipeline/.snakemake/conda/a17fd7858475ec78dc480fa36697a0cb
    shell:
        python scripts/Make-maxbin-depths.py -i /data2/PB/Metagenomics/pb-metagenomics-tools-1.6.0/HiFi-MAG-Pipeline/2-bam/atcc-msa-1003.JGI.depth.txt -o /data2/PB/Metagenomics/pb-metagenomics-tools-1.6.0/HiFi-MAG-Pipeline/2-bam/atcc-msa-1003.maxbin.depth.txt &> /data2/PB/Metagenomics/pb-metagenomics-tools-1.6.0/HiFi-MAG-Pipeline/logs/atcc-msa-1003.MaxbinDepths.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[Mon Jan 30 14:40:36 2023]
Finished job 11.
1 of 20 steps (5%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /data2/PB/Metagenomics/pb-metagenomics-tools-1.6.0/HiFi-MAG-Pipeline/.snakemake/log/2023-01-30T144032.038838.snakemake.log`

In the directory of the v1.6 pipeline, it seems that the file scripts/Make-maxbin-depths.py is not seen.

`python: can't open file 'scripts/Make-maxbin-depths.py': [Errno 2] No such file or directory
logs/atcc-msa-1003.MaxbinDepths.log (END)`

Thanks for your help.

**Comment by dportik** [comment]
Hi @YenlingPeng ,
Thanks for pointing this out. There were several scripts missing from the updated workflow. I added them, so please go ahead and download the [new release](https://github.com/PacificBiosciences/pb-metagenomics-tools/releases/tag/v1.6.1) to obtain the updated script bin. 

Please let me know if you experience any other issues.

**Comment by YenlingPeng** [comment]
Hi @dportik,

I downloaded the new version and ran the process again.
When I try to run concoct I get the error:

`Traceback (most recent call last):
  File "/data2/PB/Metagenomics/pb-metagenomics-tools-1.6.1/HiFi-MAG-Pipeline/.snakemake/conda/e5bf84c8149cdac98e6448219decc368/bin/concoct", line 6, in <module>
    import vbgmm
ModuleNotFoundError: No module named 'vbgmm'

logs/atcc-msa-1003.ConcoctAnalysis.log(END)`

I think it's something with how python locates it's internal modules.
May I know how to fix it?

Many thanks for your help and your quickness.

**Comment by dportik** [comment]
Hi @YenlingPeng ,
This was a known issue with Concoct (see [here](https://github.com/BinPro/CONCOCT/issues/181#issuecomment-509917681)). I tested the solution proposed in that thread and it worked for our systems. The environment recipe that is in the workflow (e.g., the `concoct.yml` file) contains that solution so I am unsure why this is happening.

I am planning on phasing out Concoct in the next release as I continue to test binning algorithms.

**Comment by dportik** [comment]
Hi @YenlingPeng ,
The newest version of HiFi-MAG-Pipeline is now available. Binning includes MetaBat2 and SeminBin2. Concoct and MaxBin2 have been retired, so this should end the issue.

I would encourage you to use this new version (v2.0.0), as it implements a "completeness-aware" strategy that outperforms all other versions of this pipeline. You can find more details [here](https://github.com/PacificBiosciences/pb-metagenomics-tools/blob/master/docs/Tutorial-HiFi-MAG-Pipeline.md).
