### ISSUE TITLE
Incorrect version dependency for diamond blastx --fast usage

### ISSUE THREAD

**Issue by markb729** [PacificBiosciences/pb-metagenomics-tools#37]
The existing dependency version of diamond (>= 2.0.8) is incompatible with the --fast switch, used in Taxonomic-Profiling_Diamond-Megan release v1.6.0. Switch --fast was implemented in diamond v2.0.10. Naive alteration to >=2.0.10 breaks many other dependencies but can be hacked with --conda-create-envs-only and replacing with the newest version of diamond (2.0.15) in the appropriate Conda environment.

**Comment by dportik** [comment]
Thanks for the detailed report. I did not encounter this issue when my environment was built, but I can create separate environments to prevent potential collisions. I'll do some testing this week and let you know when the fix is in place.

**Comment by dportik** [comment]
Fixed in #66
