### ISSUE TITLE
fasta or fastq?

### ISSUE THREAD

**Issue by PeymanDerik** [PacificBiosciences/pb-metagenomics-tools#38]
Hi

In the tutorial for Taxonomic-Profiling-Diamond-Megan, it says "Include all input HiFi fasta files (SAMPLE.fasta) in the inputs/ folder",  but the files I received from PacBio are fq.gz.  Should I change the format of the files?!! 

Thanks

**Comment by dportik** [comment]
Hello @PeymanDerik ,
Yes the required format is fasta. If you are looking for a simple tool for converting formats I recommend [seqtk](https://github.com/lh3/seqtk).

**Comment by gabridinosauro** [comment]
Hello! maybe you should specify that in the tutorial, it is not clear, everyone gets fastq... thanks!

**Comment by dportik** [comment]
Hi @gabridinosauro,
This information is present in the tutorial (quick start and analysis configuration sections).

[Quick Start](https://github.com/PacificBiosciences/pb-metagenomics-tools/blob/master/docs/Tutorial-Taxonomic-Profiling-Diamond-Megan.md#quick-start-)
`Include all input HiFi fasta files (SAMPLE.fasta) in the inputs/ folder. These can be files or symlinks.`

[Configuring the Analysis](https://github.com/PacificBiosciences/pb-metagenomics-tools/blob/master/docs/Tutorial-Taxonomic-Profiling-Diamond-Megan.md#sample-configuration-file-configssample-configyaml)
`All samples specified in the sample configuration file must have a fasta file of HiFi reads (SAMPLE.fasta) in the inputs/ folder. `

**Comment by gabridinosauro** [comment]
Hi @dportik 
Thanks for the reply!
yes it is but it is unclear that we can simply just convert our fastq files to fasta. I am trying to run the pipeline and I was unsure on what to do until I found this post, I thought so but was not 100% sure.

Just a suggestion to make it easier to follow, hopefully I am not sounding annoying :).

Gabri
