### ISSUE TITLE
Error in rule RunDiamond

### ISSUE THREAD

**Issue by PeymanDerik** [PacificBiosciences/pb-metagenomics-tools#39]
Hello

When I execute the workflow I get this error:

Error in rule RunDiamond:
    jobid: 4
    output: /home/biodf/Documents/Peyman/Taxonomic-Profiling-Diamond-Megan/2-diamond/BiocA2.0.sam
    log: /home/biodf/Documents/Peyman/Taxonomic-Profiling-Diamond-Megan/logs/BiocA2.0.RunDiamond.log (check log file(s) for error message)
    conda-env: /home/biodf/Documents/Peyman/Taxonomic-Profiling-Diamond-Megan/.snakemake/conda/feb041136883765b3402cabf9c9f6782
    shell:
        diamond blastx -d /home/biodf/Documents/Peyman/NCBI/diamond_nr_db.dmnd -q /home/biodf/Documents/Peyman/Taxonomic-Profiling-Diamond-Megan/1-chunks/BiocA2.fasta_chunk_0000000 -o /home/biodf/Documents/Peyman/Taxonomic-Profiling-Diamond-Megan/2-diamond/BiocA2.0.sam -f 101 -F 5000 --fast --range-culling --top 5 -b 12 -p 24 2> /home/biodf/Documents/Peyman/Taxonomic-Profiling-Diamond-Megan/logs/BiocA2.0.RunDiamond.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

Also in the log files, it says: "Error: Invalid option: fast"

Could you please let me know what this means?
Thanks

**Comment by dportik** [comment]
Hi @PeymanDerik,
This was a leftover parameter setting from an experiment with diamond. It was mentioned in #37 that the `--fast` setting was incompatible with the version of diamond being installed. 

I just updated the `Snakefile-diamond-megan` file in the repo to remove this flag. You can use this new snakefile and the error should not persist.
