### ISSUE TITLE
Error in checkm: argparse.ArgumentTypeError: The value of --tmpdir must be a valid directory

### ISSUE THREAD

**Issue by dgg32** [PacificBiosciences/pb-metagenomics-tools#4]
Hi. Today, when I run the pipeline, it failed at checkm with the error:

`argparse.ArgumentTypeError: The value of --tmpdir must be a valid directory`

It appeared at the step:

`checkm data setRoot /opt/hpcopt/sixing/checkm_data/ &> logs/661.RunCheckM-Root.log && checkm lineage_wf -x fa -t 24 --pplacer_threads 12 --tmpdir /scratch 2-metabat-bins/661/ 3-checkm/661/ &> logs/661.RunCheckM-Run.log`

It can be solved by removing the "--tmpdir /scratch" part in the checkm command.

**Comment by dportik** [comment]
Thanks for bringing this to my attention. The flag is set for usage on HPC and assumes you have access to `/scratch`, which may not be available for all users. 

Are you running this via HPC or locally?

I can add an argument in the config file that allows the user to specify the location of `--tmpdir`. This can provide an easy workaround if `/scratch` is not a valid option. The `--tmpdir` flag helps reduce memory requirements and is generally desirable to use. Alternatively, if you do not want to invoke this option, you can remove the flag from the call string in the checkm rule in the snakefile, as you've done here.

**Comment by dportik** [comment]
I went ahead and made the temporary directory location specifiable in the config file. You can download the updated config file and snakefile for the Genome-Binning-Pipeline to use this option.

Just as a follow up, did you also encounter an issue in the `RunGTDBTkIndividual` and `RunGTDBTkFull` rules? They also have defaults for the `--scratch_dir` flag set to `/scratch`. If you do not have access to `/scratch`, this will cause the same errors in these step. You can use the `tmpdir` parameter in the config file to specify a temporary directory (used in the checkm and gtdb steps), or you can edit the call for the gtdb rules if you prefer not to use the `--scratch_dir` option.

**Comment by dgg32** [comment]
Hi dportik. Thank you for the reply.

Yes, I used it on HPC, however the scratch is mounted at /home/scratch.

Once I realize the problem, I went ahead and remove all the /scratch in the snakemake file. The job finished.

**Comment by dportik** [comment]
I understand the issue. If you would like to use `/home/scratch` for the temporary writing in CheckM and GTDB-Tk, you can download the updated Genome-Binning-Pipeline snakefile and main config file. In the config file, just specify `/home/scratch` in the argument at the top called `tmpdir:`. This will allow the `/home/scratch` to be used for all steps involving a temporary writing flag. 

I will close this issue now.
