### ISSUE TITLE
Error in rule MakeRMAunfiltered

### ISSUE THREAD

**Issue by PeymanDerik** [PacificBiosciences/pb-metagenomics-tools#40]
Hi

When I execute the workflow I get this error:

/home/biodf/Documents/Peyman/megan/tools/sam2rma: line 44: /home/biodf/megan/jre/bin/java: No such file or directory

Could you please let me know what this means?

Thank you

**Comment by dportik** [comment]
Hi @PeymanDerik ,
It looks like you are missing java, which is required to run the `sam2rma` program.

**Comment by PeymanDerik** [comment]
Thanks. I am new in metagenomics and don't know how to fix it. Could you please help me with this and explain it in more details? If I just install JDK on my ubuntu then I can run the workflow or I need to add the directory of java somewhere in the database file?
