### ISSUE TITLE
manipulating final graphs of HiFi Mag pipeline

### ISSUE THREAD

**Issue by Htrivett** [PacificBiosciences/pb-metagenomics-tools#44]
I have used V2 of the pipeline, and the graphs are downloading without the full key (picture attached) is there a way to change this to get the key in full view?

[Sample1_V2.GenomeSizes-Depths.pdf](https://github.com/PacificBiosciences/pb-metagenomics-tools/files/10849477/Sample1_V2.GenomeSizes-Depths.pdf)

**Comment by dportik** [comment]
Hi @Htrivett ,
For plots with many MAGs, the legend will grow exponentially with a continuous variable such as GC content. That is why the legend is locked to a set number of levels.

If you need to see all the levels, you can modify the `Plot-Figures.py` in lines 100-101 to add the following legends argument:

```
    ax = sns.scatterplot(x="Genome_Size", y="Avg_Depth", data=df, hue=df["GC_Content"], palette="inferno",
                         s=100, alpha=0.7, edgecolor="black", linewidth=1)


    ax = sns.scatterplot(x="Genome_Size", y="Avg_Depth", data=df, hue=df["GC_Content"], palette="inferno",
                         s=100, alpha=0.7, edgecolor="black", linewidth=1, legend="full")
```

The GC content is also easily accessible in the `sample.HiFi_MAG.summary.txt` file.
