### ISSUE TITLE
Error in rule CopyDAStoolBins:

### ISSUE THREAD

**Issue by jmartinsjrbr** [PacificBiosciences/pb-metagenomics-tools#45]
I was running HiFi MAG pipeline and there was an error in rule "CopyDAStoolBins. I checked on Snakefile-hifimags.smk file and found that at line 351 is missing a slash just before *.fa like bellow:

"cp {input.binsdir}*.fa {input.copydir} 2> {log} && touch {output}"

I have replaced the line above by including a slash before *.fa:

"cp {input.binsdir}/*.fa {input.copydir} 2> {log} && touch {output}"

Now the pipeline finishes without errors.

**Comment by dportik** [comment]
Hi @jmartinsjrbr ,
Thanks for your patience. This was fixed in #48 .
