### ISSUE TITLE
Error in rule GTDBTkAnalysis：PplacerException

### ISSUE THREAD

**Issue by YenlingPeng** [PacificBiosciences/pb-metagenomics-tools#46]
Dear pb-metagenomics-tools support team,

I was running HiFi MAG pipeline and there was an error in rule "GTDBTkAnalysis. 
I checked on [2023-03-09T142429.413389.snakemake.log](https://github.com/PacificBiosciences/pb-metagenomics-tools/files/10928747/2023-03-09T142429.413389.snakemake.log). 

The error message is as follows:
`Error in rule GTDBTkAnalysis:
    jobid: 21
    output: /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/7-gtdbtk/atcc-msa-1003/align, /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/7-gtdbtk/atcc-msa-1003/classify, /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/7-gtdbtk/atcc-msa-1003/identify, /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/7-gtdbtk/atcc-msa-1003/atcc-msa-1003.Complete.txt
    log: /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/logs/atcc-msa-1003.GTDBTkAnalysis.log (check log file(s) for error message)
    conda-env: /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/.snakemake/conda/bb4264a0bcbf30c90d0a5e5f8b6acc98
    shell:
        GTDBTK_DATA_PATH=/data2/PB/Metagenomics/GTDB-Tk/release207_v2 gtdbtk classify_wf --batchfile /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/6-checkm2/atcc-msa-1003/atcc-msa-1003.GTDBTk_batch_file.txt --out_dir /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/7-gtdbtk/atcc-msa-1003/ -x fa --prefix atcc-msa-1003 --cpus 3 --pplacer_cpus 3 &> /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/logs/atcc-msa-1003.GTDBTkAnalysis.log && touch /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/7-gtdbtk/atcc-msa-1003/atcc-msa-1003.Complete.txt
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job GTDBTkAnalysis since they might be corrupted:
/data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/7-gtdbtk/atcc-msa-1003/align, /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/7-gtdbtk/atcc-msa-1003/classify, /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/7-gtdbtk/atcc-msa-1003/identify
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/.snakemake/log/2023-03-09T142429.413389.snakemake.log`

At the same time, I also checked the [atcc-msa-1003.GTDBTkAnalysis.log](https://github.com/PacificBiosciences/pb-metagenomics-tools/files/10928729/atcc-msa-1003.GTDBTkAnalysis.log)

`ERROR: Controlled exit resulting from an unrecoverable error or warning. EXCEPTION: PplacerException
  MESSAGE: An error was encountered while running pplacer.`

**Server information**
CPU: `grep -m 1 "^model name" /proc/cpuinfo && grep -c "^processor" /proc/cpuinfo`
model name	: Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz
128

RAM: `grep "^MemTotal" /proc/meminfo`
MemTotal:       527592328 kB

OS: `cat /etc/os-release`
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

In addition, I can't check the log file of pplacer, like `pplacer.backbone.bac120.out `mentioned in `atcc-msa-1003.GTDBTkAnalysis.log`, because the relay folder under the 7-gtdbtk/atcc-msa-1003/ directory will be deleted automatically.

I have tried using `--scratch_dir `and `--pplacer_cpus 1 `parameters in Snakefile-hifimags.smk, but it doesn't work.

**Comment by dportik** [comment]
Hi @YenlingPeng ,
I cannot reproduce this error on my end. This could be system specific and is related to pplacer implemented in GTDB-Tk.

You will need to ensure that you are providing a sufficient number of cpus for the `--pplacer_cpus` flag (1 will not work, 24-32 is recommended) if you add that. 

If that does not work, I suggest opening an issue with GTDB-Tk directly ([here](https://github.com/Ecogenomics/GTDBTk/issues)). I do not support or maintain that software and cannot help troubleshoot beyond the advice above.
