### ISSUE TITLE
what's the difference between filtered and unfiltered in taxonomic-profiling-minimap-megan

### ISSUE THREAD

**Issue by ye00ye** [PacificBiosciences/pb-metagenomics-tools#47]
Thanks for developing these series of tools, and I want to ask  what's the difference between filtered result and unfiltered result in taxonomic-profiling-minimap-megan.

**Comment by dportik** [comment]
Hi @ye00ye ,
From the [documentation](https://github.com/PacificBiosciences/pb-metagenomics-tools/blob/master/docs/Tutorial-Taxonomic-Profiling-Diamond-Megan.md#sam2rma):

`--minSupportPercent` argument controls the minimum **percent** of assigned reads required to report a taxon. The default for this pipeline is 0.01 (best tradeoff between precision and recall). Note that a second unfiltered RMA file is produced using a value of 0 (enabling all read-hits to be reported).
