### ISSUE TITLE
CreateCondaEnvironmentException

### ISSUE THREAD

**Issue by BardeenD** [PacificBiosciences/pb-metagenomics-tools#51]
Hello

I am executing the workflow for HiFi-MAG and I get this error. Could you please help me to fix this?  I used Canu for assembly. Thanks.

CreateCondaEnvironmentException:
Could not create conda environment from /home/biodf/Documents/Analysis for Canu/pb-metagenomics-tools/HiFi-MAG-Pipeline/envs/dastool.yml:
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
ERROR conda.core.link:_execute(740): An error occurred while installing package 'bioconda::das_tool-1.1.3-r41hdfd78af_0'.
Rolling back transaction: ...working... done

LinkError: post-link script failed for package bioconda::das_tool-1.1.3-r41hdfd78af_0
location of failed script: /home/biodf/Documents/Analysis for Canu/pb-metagenomics-tools/HiFi-MAG-Pipeline/.snakemake/conda/5ae22578426242683d73ff86f779e6a0/bin/.das_tool-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: /home/biodf/Documents/Analysis for Canu/pb-metagenomics-tools/HiFi-MAG-Pipeline/.snakemake/conda/5ae22578426242683d73ff86f779e6a0/bin/.das_tool-post-link.sh: line 11: $PREFIX/.messages.txt: ambiguous redirect

return code: 1

()

**Comment by dportik** [comment]
Hi @BardeenD ,
It looks like there is something wrong with your conda. It is crashing while trying to install the conda environments for the steps. I would recommend updating your conda to the latest version and trying again.

I am unable to reproduce this error.
