### ISSUE TITLE
How to change tmpdir from /scratch to a specific directory I've made

### ISSUE THREAD

**Issue by eag-microbio** [PacificBiosciences/pb-metagenomics-tools#52]
Hello!
I am new to using this pipeline as well as using python so I'm sorry if this is really basic question. I am running this on a lab server that is rented through the university I'm working at. I have been asking some of the support staff here for help, but they said I should ask the developer at this point. 

I am trying to run the full snakemake command but I'm running into issues with the semibin command. I know I do not have /scratch on this server, so I've tried making a temporary directory myself but I don't know how to write it into the commands in the Snakefile-hifimags.smk file. 

In my config.yaml file I have specified that I have a temporary directory that I've created (attached), how do I make the Snakefile-hifimags.smk file reflect this?  

I've shared the command I've run & the output I get after. I've also attached the config.yaml file and Snakefile as .txt files because they wouldn't upload the other formats. In the Snakefile, I had tried to specify the temporary directory in Line 291 but I don't think I'm doing it correctly. 
Thank you for your time!
Emily 

**COMMAND I AM USING:** 
$ snakemake --snakefile Snakefile-hifimags.smk --configfile configs/Sample-Config.yaml -j 50 --use-conda

**OUTPUT:** 
Config file config.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 50
Rules claiming more threads will be scaled down.
Job stats:
[config.yaml.txt](https://github.com/PacificBiosciences/pb-metagenomics-tools/files/11044308/config.yaml.txt)
[Snakefile-hifimags.smk.txt](https://github.com/PacificBiosciences/pb-metagenomics-tools/files/11044309/Snakefile-hifimags.smk.txt)

job                   count    min threads    max threads
------------------  -------  -------------  -------------
AssessCheckm2Bins         1              1              1
Checkm2BinAnalysis        1             24             24
CloseCheckm2Fork          1              1              1
ConvertJGIBamDepth        1              1              1
CopyDAStoolBins           1              1              1
DASinputMetabat2          1              1              1
DASinputSemiBin2          1              1              1
DAStoolAnalysis           1             24             24
IndexBam                  1             24             24
JGIBamDepth               1              1              1
Metabat2Analysis          1             12             12
SemiBin2Analysis          1             48             48
all                       1              1              1
total                    13              1             48

Select jobs to execute...

[Wed Mar 22 14:57:33 2023]
rule SemiBin2Analysis:
    input: /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/1-long-contigs/SSmidBS_asm/SSmidBS_asm.incomplete_contigs.fasta, /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/2-bam/SSmidBS_asm.bam
    output: /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/3-semibin2/SSmidBS_asm/bins_info.tsv, /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/3-semibin2/SSmidBS_asm
    log: /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/logs/SSmidBS_asm.SemiBin2Analysis.log
    jobid: 12
    benchmark: /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/benchmarks/SSmidBS_asm.SemiBin2Analysis.tsv
    reason: Missing output files: /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/3-semibin2/SSmidBS_asm
    wildcards: sample=SSmidBS_asm
    threads: 48
    resources: tmpdir=/tmp

Activating conda environment: .snakemake/conda/b61cd0a1b0435eb8912280a206fd45d1_
[Wed Mar 22 14:57:33 2023]
Error in rule SemiBin2Analysis:
    jobid: 12
    input: /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/1-long-contigs/SSmidBS_asm/SSmidBS_asm.incomplete_contigs.fasta, /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/2-bam/SSmidBS_asm.bam
    output: /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/3-semibin2/SSmidBS_asm/bins_info.tsv, /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/3-semibin2/SSmidBS_asm
    log: /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/logs/SSmidBS_asm.SemiBin2Analysis.log (check log file(s) for error message)
    conda-env: /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/.snakemake/conda/b61cd0a1b0435eb8912280a206fd45d1_
    shell:
        SemiBin single_easy_bin -i /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/1-long-contigs/SSmidBS_asm/SSmidBS_asm.incomplete_contigs.fasta -b /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/2-bam/SSmidBS_asm.bam -o /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/3-semibin2/SSmidBS_asm --self-supervised --sequencing-type=long_reads --compression=none -t 48 --tag-output semibin2 soil --verbose --tmpdir=/local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/tmpdir_pb &> /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/logs/SSmidBS_asm.SemiBin2Analysis.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job SemiBin2Analysis since they might be corrupted:
/local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/3-semibin2/SSmidBS_asm
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-03-22T145717.343967.snakemake.log
(base) [eag252@cbsubushley HiFi-MAG-Pipeline]$ snakemake --snakefile Snakefile-hifimags.smk --configfile configs/Sample-Config.yaml -j 50 --use-conda
Config file config.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 50
Rules claiming more threads will be scaled down.
Job stats:
job                   count    min threads    max threads
------------------  -------  -------------  -------------
AssessCheckm2Bins         1              1              1
Checkm2BinAnalysis        1             24             24
CloseCheckm2Fork          1              1              1
ConvertJGIBamDepth        1              1              1
CopyDAStoolBins           1              1              1
DASinputMetabat2          1              1              1
DASinputSemiBin2          1              1              1
DAStoolAnalysis           1             24             24
IndexBam                  1             24             24
JGIBamDepth               1              1              1
Metabat2Analysis          1             12             12
SemiBin2Analysis          1             48             48
all                       1              1              1
total                    13              1             48

Select jobs to execute...

[Wed Mar 22 14:59:44 2023]
rule SemiBin2Analysis:
    input: /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/1-long-contigs/SSmidBS_asm/SSmidBS_asm.incomplete_contigs.fasta, /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/2-bam/SSmidBS_asm.bam
    output: /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/3-semibin2/SSmidBS_asm/bins_info.tsv, /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/3-semibin2/SSmidBS_asm
    log: /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/logs/SSmidBS_asm.SemiBin2Analysis.log
    jobid: 12
    benchmark: /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/benchmarks/SSmidBS_asm.SemiBin2Analysis.tsv
    reason: Missing output files: /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/3-semibin2/SSmidBS_asm
    wildcards: sample=SSmidBS_asm
    threads: 48
    resources: tmpdir=/tmp

Activating conda environment: .snakemake/conda/b61cd0a1b0435eb8912280a206fd45d1_
[Wed Mar 22 14:59:45 2023]
Error in rule SemiBin2Analysis:
    jobid: 12
    input: /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/1-long-contigs/SSmidBS_asm/SSmidBS_asm.incomplete_contigs.fasta, /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/2-bam/SSmidBS_asm.bam
    output: /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/3-semibin2/SSmidBS_asm/bins_info.tsv, /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/3-semibin2/SSmidBS_asm
    log: /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/logs/SSmidBS_asm.SemiBin2Analysis.log (check log file(s) for error message)
    conda-env: /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/.snakemake/conda/b61cd0a1b0435eb8912280a206fd45d1_
    shell:
        SemiBin single_easy_bin -i /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/1-long-contigs/SSmidBS_asm/SSmidBS_asm.incomplete_contigs.fasta -b /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/2-bam/SSmidBS_asm.bam -o /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/3-semibin2/SSmidBS_asm --self-supervised --sequencing-type=long_reads --compression=none -t 48 --tag-output semibin2 soil --verbose --tmpdir=/local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/tmpdir_pb &> /local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/logs/SSmidBS_asm.SemiBin2Analysis.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job SemiBin2Analysis since they might be corrupted:
/local/workdir/eag252/PacBio/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/3-semibin2/SSmidBS_asm
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-03-22T145942.016029.snakemake.log

**Comment by dportik** [comment]
Hi @eag-microbio ,
If you want to use a different temporary directory, then you would just specify this in the `config.yaml` file. 

For example:
```
# The path to use as the temporary directory to write large files to, which is used for
# SemiBin2 and GTDB-Tk. If you do not have access to "/scratch" on HPC or are running
# snakemake locally, change to a valid directory.
tmpdir: "/scratch"
```
change to something else:
```
# The path to use as the temporary directory to write large files to, which is used for
# SemiBin2 and GTDB-Tk. If you do not have access to "/scratch" on HPC or are running
# snakemake locally, change to a valid directory.
tmpdir: "/another/location/dir"
```

The config file will auto-populate this value for semibin2 and gtdb-tk. That is the beauty of using the config file. 
You should **not** edit the snakemake file.

Try this and see if it runs correctly. 

If another error occurs for semibin, you should send the `/logs/SAMPLE.SemiBin2Analysis.log` file. The error message will be recorded in greater detail here.

**Comment by eag-microbio** [comment]
Thank you! I had the the tmpdir path in the config file as you said, but the error actually ended up being the way I was calling the environment for SemiBin. I had just included "soil" instead of "--environment= soil" 

I've just gotten the pipeline to run, and summary shows that none of the bins passed filtering in CheckM2.

Am I able to change the parameters for this? I see in the config file I can change the size of contig to below 500k (L. 19), and I could change the completeness from 93 to 90 (L. 23). 
Or should I go back to the assembly and see if a different assembly may work better?

**Comment by dportik** [comment]
Hi @eag-microbio ,

It would be helpful if you could answer the following questions so I can provide you with more guidance:

+ Are you working with HiFi data? 

+ What is your average read length, number of reads, and total data yield?

+ What method did you use for assembly?

**Comment by eag-microbio** [comment]
Hi @dportik ,
The data files that I have gotten back from the sequencing center all mention that it is "hifi"data. So, that makes me pretty confident that I am working with HiFi data. I've never used PacBio data before, so I'm simply going off of what the files and emails say from the sequencing facility. Please let me know if I am overlooking something! 

My samples are of soil metagenomes. I am working on one sample at the moment, but I had 2 samples sequenced on a SMRT cell. 
- The zipped fastq file is 7GB, I ran fastqc on the zipped fastq file. Total sequences: 1028040, Sequence lengths range between 57-36413.
- I used hifiasm-meta for the assembly. After assembly I have 5175 contigs. The longest 170k and the shortest is 8k. 

I'm wondering if I don't have enough sequencing depth to form any meaningful MAGS/bins because the soil community is complex? 

Thank you for your help with this! I really appreciate it!

**Comment by dportik** [comment]
Hi @eag-microbio,
Thanks for the responses here. I think you are on the right track with everything you've done, and assembling with hifiasm-meta is a great choice. Soil tends to be extremely diverse and would benefit from high sequencing depth for assembly, but it is hard to know ahead of time how much depth is sufficient.

In the pipeline there are two major steps involved with identifying MAGs:
1. Identify long contigs that are highly complete.
2. Perform binning and QC on the remaining incomplete contigs.

For phase 1, the following options in the `config.yaml` apply:
```
# The settings below will affect the completeness-aware binning step.
completeness_aware:
  # Minimum size of a contig to consider for completeness scores. The default value is set to 500kb.
  # This value should NOT be increased. It could be decreased, but genomes <500kb are not expected and
  # contigs this size will likely fail the completeness filtering.
  min_length: 500000

  # Minimum completeness score (from CheckM2) to mark a contig as "complete" and place 
  # it in a distinct bin. This should not be lowered below 90.
  min_completeness: 93
```
If you do not have any contigs >500,000 bp, you will not have any results for this step. Based on what you've described, 170kb is the upper size limit for your contigs, so changing the above values will not help. There just aren't any long, complete bacterial contigs (and that's okay).


Your MAGs will therefore have to come from phase 2. For phase 2 filtering, the following options apply:
```
filters:
  # Set the quality filters that are applied to MAGs
  # The minimum percent completeness for a genome bin.
  min_completeness: 70

  # The maximum percent contamination for a genome bin.
  max_contamination: 10

  # The maximum number of contigs allowed in a genome bin.
  max_contigs: 20
```
These values are also measured with CheckM2. 

From your first pass analysis, it seems there aren't any bins that pass these criteria. 

To understand why, you can look in the `6-checkm2/SAMPLE/checkm2/SAMPLE.quality_report.tsv`. 
This has metadata for all the bins (even those that failed), including the scores for the above measures. 
There may be some bins that lie on the border of passing, but are failing one score.
It is possible that lowering the above thresholds could rescue some lower quality bins, but that file will tell you for certain and guide you towards better settings.

Even incomplete bins can be useful for some downstream analyses, so it is worth following up on!
