### ISSUE TITLE
GTDB-Tk reference data appears to have moved

### ISSUE THREAD

**Issue by xfengnefx** [PacificBiosciences/pb-metagenomics-tools#6]
Hi, 

Just want to quickly mention that the current GTDB reference file release (referred by Hifi-MAG-Pipeline's [tutorial page](https://github.com/PacificBiosciences/pb-metagenomics-tools/blob/master/docs/Tutorial-HiFi-MAG-Pipeline.md)) seems to have migrated to https://data.gtdb.ecogenomic.org/releases/release95/95.0/auxillary_files/gtdbtk_r95_data.tar.gz , according to their bioconda bundle's [script](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/gtdbtk/download-db.sh) or [doc](https://ecogenomics.github.io/GTDBTk/installing/bioconda.html#step-3-download-and-alias-the-gtdb-tk-reference-data). 

The [original link](https://data.ace.uq.edu.au/public/gtdb/data/releases/release95/95.0/auxillary_files/gtdbtk_r95_data.tar.gz) is alive for browsers and is still in GTDB's [doc](https://ecogenomics.github.io/GTDBTk/installing/index.html), but currently throws 403 at wget even with --referer --user-agent set.

Thanks!

edit: typo

**Comment by dportik** [comment]
Thanks for raising this issue! It is unfortunate that there are conflicting links for the GTDB reference. The updated link you found is now provided in the HiFi-MAG-Pipeline documentation.

**Comment by dportik** [comment]
@xfengnefx I just tried a fresh snakemake run on our HPC:
`snakemake --snakefile Snakefile-hifimags --configfile configs/Sample-Config.yaml --use-conda --cluster "qsub -q bigmem -pe smp {threads} -V -cwd -S /bin/bash -o HPC_logs/ -e HPC_logs/" -j 24 --jobname "{rule}.{wildcards}.{jobid}" --latency-wait 60 --verbose` 

I am using conda 4.6.3 and snakemake 5.26.1.

During environment download and setup I saw the following:

```
Building DAG of jobs...
Creating conda environment envs/checkm.yml...
Downloading and installing remote packages.
Using Anaconda API: https://api.anaconda.org

checkm data setRoot /dept/appslab/projects/old/2021/dp_snake-Env-test/.snakemake/conda/0bfacae2/checkm_data



Environment for envs/checkm.yml created (location: .snakemake/conda/0bfacae2)
Creating conda environment envs/gtdbtk.yml...
Downloading and installing remote packages.
...
```
Looking in `.snakemake/conda/0bfacae2/bin` I can see the several executables including `checkm`, and the run finished successfully. 

I tested a second new snakemake run with a checkm environment file using the next version up (`checkm-genome == 1.1.3`), and that also finished successfully. 

I am not seeing any issues with setting up and running the environments with conda. If you are using mamba as an alternative to conda, the proble might be with mamba.

**Comment by dportik** [comment]
I also just tried the download links for GTDB:
```
wget https://data.ace.uq.edu.au/public/gtdb/data/releases/release95/95.0/auxillary_files/gtdbtk_r95_data.tar.gz
wget https://data.gtdb.ecogenomic.org/releases/release95/95.0/auxillary_files/gtdbtk_r95_data.tar.gz
```
I did not encounter any 403 errors - they both started downloads of the relevant files. Perhaps there is an issue with server configuration?

**Comment by xfengnefx** [comment]
Just tried again, this time it worked for me as well. Interesting, maybe the server had some temporary issues. 

Thanks a lot!
