### ISSUE TITLE
KeyError during AssessCheckm2Bins

### ISSUE THREAD

**Issue by Htrivett** [PacificBiosciences/pb-metagenomics-tools#60]
PB-HiFi-Mag-Pipeline

I am running some Hifiasm-meta assemblies through the pipeline, and when I get to AssessCheckm2Bins, I seem to get a KeyError for one of the contig names. I have put hifiasm-meta assemblies through before and have not had this problem, so it may be file specific.

~/HiFi-MAG-Pipeline_V2$ cat logs/7283_metagenome_hifiasm.AssessCheckm2Bins.log
make_checkm_df: Making checkm2 dataframe.
make_depth_dict: Making depth dictionary.
add_contig_numbers_and_status: Adding contig numbers and assessing Pass/Fail filtering status.
Traceback (most recent call last):
  File "scripts/Filter-Checkm2-Bins.py", line 158, in <module>
    main()
  File "scripts/Filter-Checkm2-Bins.py", line 151, in main
    add_contig_numbers_and_status(df, depth_dict, args.bin_dir, args.min_completeness, args.max_contamination, args.max_contigs)
  File "scripts/Filter-Checkm2-Bins.py", line 86, in add_contig_numbers_and_status
    depths.append(", ".join([depth_dict[rec.id] for rec in SeqIO.parse(filename, 'fasta')]))
  File "scripts/Filter-Checkm2-Bins.py", line 86, in <listcomp>
    depths.append(", ".join([depth_dict[rec.id] for rec in SeqIO.parse(filename, 'fasta')]))
KeyError: 's3.ctg000004l'
<img width="1440" alt="Screenshot 2023-06-06 at 11 28 49" src="https://github.com/PacificBiosciences/pb-metagenomics-tools/assets/122980545/18caea08-53dc-47e6-83c0-539c583293d0">

**Comment by dportik** [comment]
Hi @Htrivett,
Thanks for your patience, we've started our summer conference season and have been traveling. 

I have not encountered this issue. During this step, the contigs within each bin fasta file are being looked at. There is a step immediately before that uses the same logic, so it is puzzling as to why this error occurs here (and not in previous calls). 

If you try deleting the checkm2 results for this step, can you re-run without an error?

**Comment by dportik** [comment]
Hi @Htrivett,
Do you have any updates on this issue?

**Comment by Htrivett** [comment]
Hi @dportik 

I ended up reassembling again and going through the pipeline again. Seemed to be a file error during assembly step.

Thanks
