### ISSUE TITLE
Minimap2 issue with map-hifi

### ISSUE THREAD

**Issue by ivwonter** [PacificBiosciences/pb-metagenomics-tools#67]
Please leave the headers below and replace the relevant text. This will expedite addressing the ticket. 

**Name the workflow**
HiFi-MAG-Pipeline

**Describe the bug**
Older version of minimap2 (v2.17-r941) in conda environment does not seem to be compatible with the '-x mag-hifi' preset causing the pipeline to fail. Recommend changing the version of minimap2 to the latest release (anything from v2.22 onwards).

**Expected behavior**
Expected pipeline and mapping to run as normal

**Screenshots**
Activating conda environment: .snakemake/conda/6449c2824f4382d1b8f2a13dc4e35f69_
[Fri Sep 22 16:01:04 2023]
Error in rule MinimapIndex:
    jobid: 22
    input: ...
    output: ...
    log: ...
    conda-env: ...
    shell: minimap2 -x map-hifi -t 20 -d ...
(one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-09-22T160100.152624.snakemake.log

**Log files**
[ERROR] unknown preset 'map-hifi'

**Comment by baotg080599** [comment]
name: samtools_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - samtools == 1.10
  - minimap2 

paste this overwrite into samtools.yml

**Comment by dportik** [comment]
Thanks for highlighting the issue, it was resolved in #70
