### ISSUE TITLE
duplicated key for fasta

### ISSUE THREAD

**Issue by ArthurPERE** [PacificBiosciences/pb-metagenomics-tools#73]
Hello,

In the pipeline HiFi-MAG, there is a bug when you redo the pipeline with the same parameters. 

When you have the gtbdtk is running, there is a duplicated key error, in the fasta file. I try and maybe found the source of the bug.

The bug is when there is an 5-duplicated-bins/{sample}/complete.[number].fa . Where there is an duplicate key, or multiple times the same key inside the fasta file.

for example :
```bash
grep ">ctg1272626_16x_l" 1-long-contigs/{sample}/bins/complete.1.fa 
>ctg1272626_16x_l
>ctg1272626_16x_l
>ctg1272626_16x_l
```

Inside the contig file there is only one contig with this name.

I retrace the bug and I fall on this scripts :

[HiFi-MAG-Pipeline/scripts/Fasta-Make-Long-Seq-Bins.py](https://github.com/PacificBiosciences/pb-metagenomics-tools/blob/master/HiFi-MAG-Pipeline/scripts/Fasta-Make-Long-Seq-Bins.py
)

Why open fasta files in append mode (lines 43 and 47) ? I think, because of that, it create this bug later in the pipeline.

Thank you,
Regards,
Arthur

**Comment by dportik** [comment]
Hi @ArthurPERE ,
The pipeline is designed to be run once, and not sequentially with different parameter settings. There will be many other issues beyond the one you describe here, which will cause errors downstream. I would strongly recommend that after you perform a run, you move all outputs to a different location before attempting to re-run any new analyses.
