### ISSUE TITLE
“Taxonomic-Profiling-Diamond-Megan”Does this tutorial adapt to illumina Generation II contigs after assembly

### ISSUE THREAD

**Issue by EQunSee** [PacificBiosciences/pb-metagenomics-tools#74]
Please leave the headers below and replace the relevant text. This will expedite addressing the ticket. 

**Taxonomic-Profiling-Diamond-Megan**

**Does this tutorial adapt to illumina Generation II contigs after assembly？**
What needs to be clarified? Provide a clear and concise description of what is needed to answer your question.

**I want to use “Taxonomic-Profiling-Diamond-Megan”pipeline to align the second generation contigs after assembly**

**Comment by dportik** [comment]
Hello @EQunSee ,
The `Taxonomic-Profiling-Diamond-Megan` is designed to be used with PacBio HiFi reads. 

For other possible data types, you can refer to the MEGAN user-group website for information: https://megan.cs.uni-tuebingen.de/
