### ISSUE TITLE
MissingInputException in rule CheckM2ContigAnalysis

### ISSUE THREAD

**Issue by ThenaHu** [PacificBiosciences/pb-metagenomics-tools#87]
I am using the **HiFi-MAG-Pipeline** for my analysis, and I followed the **Update Tutorial-HiFi-MAG-Pipeline.md** to download the **CheckM2 database** and specified the path correctly in the config.yaml file. However, I am still encountering the following error.

I also tried commenting out the **CheckM2 database** path in the config.yaml and the related path in Snakefile-hifimags.smk (specifically, db = config["checkm2"]["db"]), but the issue persists. How can I resolve this?

<img width="1154" alt="截圖 2024-08-30 上午9 48 39" src="https://github.com/user-attachments/assets/6408a64f-a228-4b9d-bd57-b28380427398">

**Comment by dportik** [comment]
Hi @ThenaHu ,
When you downloaded the database, did you unpack the tar file? 
Can you include the portion of the config file that contains the checkm2 parameters?

**Comment by dportik** [comment]
No response, closing for now.

**Comment by dportik** [comment]
This was indeed a bug and is fixed in [v3.3.0](https://github.com/PacificBiosciences/pb-metagenomics-tools/releases/tag/v3.3.0). Please download the newest release and post if the issue persists.
